server:
  port: 8000
spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:sqlite:servicesphere.db}
    driver-class-name: ${SPRING_DATASOURCE_DRIVER_CLASS_NAME:org.sqlite.JDBC}
  jpa:
    database-platform: ${SPRING_JPA_DATABASE_PLATFORM:org.hibernate.community.dialect.SQLiteDialect}
    hibernate:
      ddl-auto: update
    show-sql: true
